dream11/urls.py
from django.contrib import admin
from django.urls import path
from drm11 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.first,name='first'),
    path('home',views.home,name='home'),
]

drm11/models.py
from django.db import models

# Create your models here.


class prediction_new(models.Model):
    pred_date = models.DateTimeField(auto_now_add=True)
    name=models.CharField(max_length=50,unique=True)
    email=models.CharField(max_length=100,unique=True)
    team_name=models.CharField(max_length=100)
    player_name=models.CharField(max_length=100)


class prediction_archive_new(models.Model):
    pred_date = models.DateTimeField(auto_now_add=True)
    name=models.CharField(max_length=100,unique=True)
    email=models.CharField(max_length=100,unique=True)
    team_name=models.CharField(max_length=100)
    player_name=models.CharField(max_length=100)

drm11/forms.py
from django import forms
from .models import prediction_new,prediction_archive_new




class PredForm(forms.Form):
    FILTER_CHOICES= [
  ('Chennai Super Kings','Chennai Super Kings'),
('Delhi Capitals','Delhi Capitals'),
('Kings XI Punjab','Kings XI Punjab'),
('Kolkata Knight Riders','Kolkata Knight Riders'),
('Mumbai Indians','Mumbai Indians'),
('Royal Challengers Bangalore','Royal Challengers Bangalore'),
('Rajasthan Royals','Rajasthan Royals'),
('Sunrisers Hyderabad','Sunrisers Hyderabad'),
    ]

    name = forms.CharField(label='name', max_length=100 ,required=True)
    email = forms.CharField(label='email', max_length=100,required=True)
    team_name=forms.ChoiceField(choices = FILTER_CHOICES)
    player_name=forms.CharField(label='player_name', max_length=100,required=True)


    def clean(self):
        cleaned_data = self.cleaned_data
        name1=self.cleaned_data['name']
        email1=self.cleaned_data['email']
        # team_name=self.clened_data['team_name']
        # player_name=self.cleaned_data['player_name']
        for instance in prediction_new.objects.all():
            if (instance.name==name1):
                raise forms.ValidationError(name1+" already Predicted")
            elif (instance.email==email1):
                raise forms.ValidationError(email1+" already Predicted")
        
            # elif (name1==""):
            #     raise forms.ValidationError("Fill all the fields")
            # elif (email1==""):
            #     raise forms.ValidationError("Fill all the fields")
            # elif (team_name==""):
            #     raise forms.ValidationError("Fill all the fields")
            # elif (player_name==""):
            #     raise forms.ValidationError("Fill all the fields")
     
        # if email and prediction_new.objects.get(email=email):
        #     raise forms.ValidationError(email+" already Predicted")
        return cleaned_data
    # def clean_name(self):
    #     cleaned_data = self.cleaned_data
    #     if self.cleaned_data['name'].strip() == '':
    #         raise forms.ValidationError('field cannot be blank!')
    #     return cleaned_data['name']  
    #     for instance in prediction_new.objects.all():
    # 		if (instance.name==name):
    #             raise forms.ValidationError(name + ' is already added'
    #     return name
    #     # match=prediction_new.objects.get(name=name)
    #     # if(match):
            
    #     #     raise forms.ValidationError(name +" already exists")
    #     # else:
    #     #     return name
    # def clean_email(self):
        
    #     email=self.cleaned_data['email']
    #     for instance in prediction_new.objects.all():
    #         if (instance.email == email):
    #             raise forms.ValidationError(email + ' is already added')
	#     return email
       
        # match_e=prediction_new.objects.get(email=email)
        # if(match_e):
            
        #     raise forms.ValidationError(email+" already exists")
        # else:
        #     return email





    



drm11/views.py
from django.shortcuts import render
from .models import prediction_new,prediction_archive_new
from .forms import PredForm
from django import forms

# Create your views here.
def first(request):
    return render(request,'nav.html')

def home(request):
    if request.method=="POST":
        form=PredForm(request.POST)
        if form.is_valid():
            name={}
            name=request.POST['name']   
            email=request.POST['email']
            team_name=request.POST['team_name']
            player_name=request.POST['player_name']
            
            
            
            pred=prediction_new(name=name,email=email,team_name=team_name,player_name=player_name)
            pred.save()

            return render(request,'dummy.html',context={'form': form,'name':name})
        else:

            print("invalid")
        #     print (form.errors)
            error="filll All The Fields"
            return render(request,'home.html',context={'form': form})

        
    else:
        print("No Post")
        form=PredForm()
    return render(request,'home.html')


templates/dummy.html


{% load static %}
<link rel="stylesheet" href='{% static "success.css" %}' />
<div class='content'>
        <div class='fa fa-check-circle-o symbol'></div>
        <div class='title'>Thank you!</div>
        <div class='text'>Your Prediction has been received!</div>
      </div>

templates/home.html
<!-- 
<form action="home" method="post">
  {% csrf_token %}

  <div class="container">
    <h1>Welcome to Dream11</h1>
    <hr>
    <label for="name"><b>Enter your Name</b></label>
    <input type="text" placeholder="Enter Your Name" name="name" required>

    <label for="email"><b>Enter your Email</b></label>
    <input type="email" placeholder="Enter Email" name="email" required>

    <label for="player_name"><b>Predict Player</b></label>
    <input type="text" placeholder="Enter Email" name="player_name" required>

    <hr>

    <button onclick="location.href='{% url 'home' %}'" type="submit" class="home">Predict</button>
  </div>
  
</form> -->

{% load static %}
<link rel="stylesheet" href='{% static "home.css" %}' />
{% load static %}
  <script src="{% static 'home.js' %}" type="text/javascript"></script>  

<div class="user">
  <header class="user__header">
    {% load static %} 
    <img src='{% static "Untitled.png" %}' alt="Hi!" />
      
  </header>
  
  <form action="home" method="POST">


      {% csrf_token %}

      {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
      <div class="form__group">
          <input type="text" placeholder="Dream11 Username" name="name" class="form__input" required/>
      </div>
      
      <div class="form__group">
          <input type="email" placeholder="Enter Valid Email" name="email" class="form__input" required/>
      </div>
      
      <div class="form__group">
        <select class="form__input" id="id_team_name" name="team_name" required>
          <option selected disabled selected>Select Team</option>
          <option value="Chennai Super Kings" >Chennai Super Kings</option>
          <option value="Delhi Capitals">Delhi Capitals</option>
          <option value="Kings XI Punjab">Kings XI Punjab</option>
          <option value="Kolkata Knight Riders">Kolkata Knight Riders</option>
          <option value="Mumbai Indians">Mumbai Indians</option>
          <option value="Royal Challengers Bangalore">Royal Challengers Bangalore</option>
          <option value="Rajasthan Royals">Rajasthan Royals</option>
          <option value="Sunrisers Hyderabad">Sunrisers Hyderabad</option>
        </select>
      </div>
      <div class="form__group">
          
        <input type="text" placeholder="Who will be the Man of the Match?" name="player_name" class="form__input" required/>
    </div>
      
    <button class= "buttn" onclick="location.href='{% url 'home' %}'" type="submit" class="home">Predict</button>
  </form>
</div>

templates/nav.html

{% load static %}
<link rel="stylesheet" href='{% static "nav_css.css" %}' />
<header>
  <h1>
                Welcome To APTP IPL Super Predictor (AISP) - 2020
            </h1>
  <!-- <span>
                <h2>2020</h2>
  </span> -->

<div class="container red topBotomBordersOut">
  <a onclick="location.href='{% url 'home' %}'">Predict</a>
  <a href="https://www.dream11.com/download-app?pid=organiclandingpage&c=downloadapp&af_adset=mobileweb">Download Dream11 apk</a>
  
</div>
</header>